language: node_js
node_js:
- v4
before_install:
- npm install -g gulp
script:
- gulp
deploy:
  provider: npm
  email: mmarshall@nombers.io
  api_key:
    secure: diLspB69D5drGXyiJSpaQrdLbLKkQi8eS+/9vGmqpzh928g1ASm6pN64+VwA4qBRNvJO1IgfesPODC3d1mh5mkSYLU4bY/UZJNmgR+eCIc6TgoAwMaZjyoo8erx74mBh/9tZC3a5j+DcVgOsSO+fAI7fNKiqHDx0x0mcDp9TXTymRBlUz5gUJvIzTdspQKoE3Y7Jt6/2svnpIoOEfx39y9oahRN56YJrBhwVtHlxXH4dFo7Qx8T9cZQgYipw6xxHgDWAWP1dL+My9U7TS+PyetsA6p9Stu4qm9COv49OcJZdPNrajBJYX1qudSohnW2AR7s2Nk3o2x9pJpDijTRN/P5/Mmkfd3olZDsY5KFj2oaQ0hrlwjuwwbD5GrkNIxRkNL5Aasp6kmEIag83o2lTGSwnef/Y3UEuoRwvPaVo7RBtGGto4DnxG1XgdPE3he9cxfCjobn1hMDKZ+Qu4K8FF5G9jbfDHt03D/IM4iG03m93T3jUCQ70JhgG7MhX/uvRCr6ovrmQOWbrc70Iy5wsVoxMwsaZMcYDxBH7m7LyldQ/hS0BXgbct7rOUB+ZTGYb70Zoxs7xgnx4N010I+Bk2sW142exyfKiHXZVyJkW9sv8r2mk/PToqekl13GIIoi1L7I0/oRooL8WsHkG8JzkwVQw13diq2f+wlZr32ZFLNo=
  on:
    tags: true
    repo: nombers/generator-lambda6
